In [1]:
import numpy as np

In [4]:
from numpy import *

In [6]:
M = array([[0, 1, 2], [3, 4, 5],[6, 7, 8]])
M

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [7]:
print (sum(range(5),-1))

10


In [10]:
from numpy import *

In [12]:
print (sum(range(5),-1))

10


In [13]:
np.sqrt(-1)==np.emath.sqrt(-1)

C:\Users\mkamardin\AppData\Local\Continuum\Miniconda2\envs\tutorial\lib\site-packages\ipykernel\__main__.py:1: RuntimeWarning: invalid value encountered in sqrt
  if __name__ == '__main__':


False

In [21]:
M=random.rand(6,5)
M

array([[ 0.06394596,  0.38541466,  0.80391685,  0.25163839,  0.06134447],
       [ 0.33881067,  0.02825193,  0.52082069,  0.58160341,  0.4548042 ],
       [ 0.95547593,  0.99247468,  0.75400184,  0.90132745,  0.51602569],
       [ 0.46376671,  0.50286995,  0.24459999,  0.15002977,  0.0050106 ],
       [ 0.571849  ,  0.59477135,  0.08201249,  0.63030094,  0.45194773],
       [ 0.17293394,  0.83570311,  0.35022568,  0.77433405,  0.13678913]])

In [25]:
mean(M[:,])


0.45256670822934614

In [54]:
N=random.rand(5,3)
H=random.rand(3,2)
N1=matrix (N)
H1=matrix (H)
N1*H1

matrix([[ 0.7776081 ,  0.46289941],
        [ 1.2483712 ,  0.82978088],
        [ 1.27942813,  0.93350587],
        [ 1.61893362,  1.24925448],
        [ 1.91975054,  1.51812784]])

In [56]:
K=random.rand(10)
K


array([ 0.97829849,  0.66012084,  0.41398045,  0.10307267,  0.6199095 ,
        0.74719607,  0.65894508,  0.15242837,  0.58230313,  0.80060491])

In [59]:
sort (K)

array([ 0.10307267,  0.15242837,  0.41398045,  0.58230313,  0.6199095 ,
        0.65894508,  0.66012084,  0.74719607,  0.80060491,  0.97829849])

In [75]:
L=random.rand(100)
L=sort(L)
L[99]=0
L

array([ 0.05840112,  0.06300564,  0.06521008,  0.08446951,  0.09537169,
        0.09971565,  0.10684213,  0.11371032,  0.12352194,  0.13385065,
        0.13948417,  0.14420156,  0.1564513 ,  0.16896187,  0.17281316,
        0.17535509,  0.17993119,  0.23296354,  0.24367718,  0.2504973 ,
        0.25403432,  0.27246727,  0.29055096,  0.30226252,  0.30836597,
        0.31573244,  0.32629833,  0.33791331,  0.34266587,  0.34369846,
        0.36121501,  0.37771514,  0.38503425,  0.38908163,  0.41163631,
        0.41436919,  0.44568267,  0.45639119,  0.45748791,  0.46924175,
        0.47020699,  0.47549069,  0.4762844 ,  0.4793552 ,  0.49248643,
        0.49325097,  0.52055936,  0.52401234,  0.54241353,  0.55785948,
        0.58965755,  0.59076472,  0.59537069,  0.60287023,  0.6041672 ,
        0.60815425,  0.60830096,  0.61309524,  0.61600864,  0.61825466,
        0.63552228,  0.64959349,  0.65397024,  0.66557999,  0.66696381,
        0.67068166,  0.68318486,  0.70775449,  0.70837159,  0.71

In [105]:
H=random.rand(4,4)
H


array([[ 0.16564166,  0.21091002,  0.68207906,  0.19006834],
       [ 0.96431362,  0.82471805,  0.89770738,  0.35055025],
       [ 0.09329685,  0.59701275,  0.28091688,  0.37729339],
       [ 0.67851563,  0.32013924,  0.59830457,  0.38146819]])

In [106]:
H_Inv=linalg.inv(H)
H_Inv

array([[-1.34758216,  0.63481069, -0.95414016,  1.03177787],
       [-0.48819869,  1.41435266,  0.97990187, -2.02565009],
       [ 2.06454861,  0.09574992, -0.55965267, -0.56313276],
       [-0.4314429 , -2.46627741,  1.75253597,  3.36944889]])

In [107]:
HH=dot(H,H_Inv)
np.around(HH)

array([[ 1.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.],
       [ 0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  1.]])